version: '3.5'

services:
  frontend:
    build: ml-kurkkumopo-frontend/
    image: ml-frontend
    ports:
    - 3000:3000
  
  backend:
    build: ml-kurkkumopo-backend/
    image: ml-backend
    ports:
    - 5000:5000
    volumes:
    - model:/src/model

  ml:
    build: ml-kurkkumopo-training/
    image: ml-training
    volumes:
    - model:/src/model
    - data:/src/data
    - images:/src/imgs

volumes:
  model:
  images:
  data: