version: "3.3"
services:
  coursematerial:
    image: slim-frontend
    ports:
      - 5000:5000
    container_name: coursematerial
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower